---
  - name: Install Zabbix on host3
    become: True
    gather_facts: False
    hosts: host3
    tasks:
      - name: Install yum utils
        yum:
          name: yum-utils
          state: present
      
      - name: Add repository docker
        shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

      - name: Install docker on host3
        yum:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose-plugin
          state: latest

      - name: Docker process start
        systemd:
          name: docker
          state: started

      - name: Zabbix image start
        shell: docker run --name some-zabbix-web-nginx-mysql -e DB_SERVER_HOST="some-mysql-server" -e MYSQL_USER="some-user" -e MYSQL_PASSWORD="some-password" -e ZBX_SERVER_HOST="some-zabbix-server" -e PHP_TZ="some-timezone" -d zabbix/zabbix-web-nginx-mysql:latest

      - name: Zabbix image start
        shell:  docker run --name some-zabbix-appliance -p 80:80 -p 10051:10051 -d zabbix/zabbix-appliance:latest
      
      - name: Add route for host
        shell: ip route add default via 192.168.56.1 dev enp0s8
        tags: inet
