---
- name: Prepare for nstall Foreman on host2 with role
  become: True
  gather_facts: True
  hosts: host2
  tasks:
    - name: Update Linux packages
      yum:
        name: '*'
        state:  latest

    - name: Firewalld off
      service:
        name: firewalld
        state: stopped

    - name: Template /etc/hosts
      template:
        src:  templates/hosts.j2
        dest: /etc/hosts

- name: Install Foreman  
  become: True
  gather_facts: False
  hosts: host2
  roles:
    - theforeman.operations.ansible_repositories
    - theforeman.operations.puppet_repositories
    - theforeman.operations.foreman_repositories
    - theforeman.operations.installer

- name: Install FreeIPA client on host2 and add in domain test.local
  become: True
  gather_facts: True
  hosts: host2
  vars:
   freeipaclient_servers:
     - host1.test.local
   freeipaclient_domain: host2.test.local
   freeipaclient_enroll_user: admin
   freeipaclient_enroll_pass: 12345678
   freeipaclient_dns_server: 192.168.56.240

  roles:
   - ctl-fed-security.freeipa-client
  tags:
   - freeipa


      # name: Add route 
      # shell: ip route add default via 192.168.56.1 dev eth1
