---
- name: Install GPG package
  package:
    name: gpg
    state: present
    update_cache: true

- name: Install Puppet repository
  apt:
    deb: "https://apt.puppet.com/puppet{{ foreman_puppet_repositories_version }}-release-{{ ansible_distribution_release }}.deb"
    state: present
  register: puppet_apt_deb_install

- name: Update apt cache if necessary
  apt:
    update_cache: true
    force_apt_get: true
  when: puppet_apt_deb_install.changed
  tags:
    - skip_ansible_lint  # skip lint since we cannot use handler, and cache must be updated immediately
